name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v0.1.0

permissions:
  id-token: write  # Required for OIDC (no need for secrets if using Trusted Publisher)
  contents: read

jobs:
  publish:
    name: Build and publish package
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tool
        run: python -m pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true  # Optional: helps with debugging if it fails
